version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Ajoutez d'autres variables d'environnement si nécessaire
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
